### ISSUE TITLE
No Accessories showing up in v2.0.0

### ISSUE THREAD

**Issue by TheEngineerGuy** [hjdhjd/homebridge-myq2#49]
Used following config:

"platforms": [{
    "platform": "myQ",
    "email": "email@email.com",
    "password": "password"
}]

But no myQ accessories are being discovered or shown in home app.

Reset homebridge persist and accessories, still no go.

EDIT: started HB in insecure mode to see if any accessories show in the web interface, and no myQ accessories show up there either.

**Comment by TheEngineerGuy** [comment]
@hjdhjd Any ideas bud?

**Comment by hjdhjd** [comment]
Read the README. :smile:

It may take up to 45 minutes or so to connect to the MyQ API. It keeps retrying every 15-20 seconds until the servers let us connect.

You'll see a message in the homebridge log when it does connect:

```
[MyQ Platform] Successfully connected to the myQ API.
```
Walk away and check in a bit later...it's not ideal, but it should work.

Let me know.

**Comment by TheEngineerGuy** [comment]
I saw that note, but a bit baffled as to why :).

**Comment by hjdhjd** [comment]
Well, now you know. :smile:

**Comment by TheEngineerGuy** [comment]
LOL! No I don't know. Is it random, or is there something funky going on to discover the accessories? I have my accessory index if that is what it is looking for.

**Comment by dxdc** [comment]
> It may take up to 45 minutes or so to connect to the MyQ API

@hjdhjd does this happen on every hb re-start or just the initial configuration?

**Comment by hjdhjd** [comment]
It's the MyQ API servers. They will randomly lockup and not issue login credentials.

**Comment by hjdhjd** [comment]
@dxdc Every restart. It's the API unfortunately. On the plus side, this wasn't happening a couple of days ago.

My suspicion is that when they shutdown all the legacy APIs, they didn't ramp up their server capacity enough and they're struggling to catch up. Again - a guess on my part, but I had zero login issues prior to 7/1 on v5 while I've been refactoring this plugin for a couple of weeks now.

**Comment by TheEngineerGuy** [comment]
O I see, so before July 7th, this was working fine. WTF!! LOL!! I wonder if this is causing problems for MyQHB as well. I gave mine away as it was horrible. This plugin was better than it.

**Comment by hjdhjd** [comment]
I have both. The hardware HB is incredibly flakey on WiFi for sure, but I seem to have wrangled that over the past few weeks too, almost by accident. That's another story for another day.

**Comment by TheEngineerGuy** [comment]
Ofcourse you did! There is a factory reset on it, if it is still physically in one piece. That is a big if! :)

**Comment by dxdc** [comment]
Amazon Key integrates with myQ. Do you know if that works more reliably? There is no hb-amazonkey project yet... (that I've found)... but could be another approach. One would think that the Amazon<-->myQ connection should be very robust. Crazy to hear that myQ's own HK device isn't working well either!

**Comment by dxdc** [comment]
Also, what about "hard coding" the devices, e.g.
`Adding new myQ garagedoor device: Garage Door Opener - CGXXXXXXXXXXX`

Could we just store `CGXXXX` as a config parameter to speed things up for future restarts?

**Comment by hjdhjd** [comment]
The issue is the API, not the accessories. The accessories themselves are cached, and you'll see them "right away" on subsequent restarts, although they will appear unreachable until they can talk to the API.

**Comment by jehrler** [comment]
What confuses me is that after adjusting the platform name and restarting...and waiting, the log says 

[GarageDoor] Successfully connected to the myQ API.
[7/3/2020, 9:59:25 PM] [GarageDoor] myQ gateway device discovered: XXXX
[7/3/2020, 9:59:25 PM] [GarageDoor] myQ garagedoor device discovered: XXXX

but no garage door showing up in accessories.

**Comment by hjdhjd** [comment]
@jehrler The accessories are there. If you're seeing the above, then the accessories are in HomeKit. Go look for them...perhaps in the default room.

**Comment by sethspergel** [comment]
I’m seeing the same thing. Logs look good but no garage door opener showing
up in my list of accessories anywhere.

**Comment by jehrler** [comment]
The opener is not listed in the Homebridge Config UI list of accessories nor in the home apps even after the all-good log entries. If I go into the iOS home app Hubs and Bridges Homebridge is there but shows only 1 accessory (my thermostat). 

Regards,

James R Ehrler

**Comment by TheEngineerGuy** [comment]
Ok, back here then, accessories not showing up. @hjdhjd . They are discovered, just not showing up.

**Comment by hjdhjd** [comment]
@TheEngineerGuy assuming you're on 2.0.5...post the logs so I can see what we're working with here.

**Comment by TheEngineerGuy** [comment]
```
[7/4/2020, 12:09:54 AM] [myQ] Successfully connected to the myQ API.
[7/4/2020, 12:09:55 AM] [myQ] myQ garagedoor device discovered: Garage Door - CGxxxxxxxxxxxx.
[7/4/2020, 12:09:55 AM] [myQ] myQ gateway device discovered: Garage Door - GWxxxxxxxxxxxxxx.
```

**Comment by shamoon** [comment]
@jehrler The Config UI X issue is noted here: #55 , the author will have to add back the file. As for the no accessories there are multiple related issues I believe: #51 & #57

**Comment by hjdhjd** [comment]
I think @shamoon was too quick on the draw there. LOL. @TheEngineerGuy stop homebridge, delete the accessories cache and restart. Give that a whirl. The accessories cache is at `~/.homebridge/accessories/cachedAccessories`

**Comment by TheEngineerGuy** [comment]
I did this a couple of times. no go.

```
sudo hb-service stop
ls /var/lib/homebridge/
sudo rm -dR /var/lib/homebridge/accessories
sudo rm -dR /var/lib/homebridge/persist
ls /var/lib/homebridge/
sudo hb-service start
```

**Comment by shamoon** [comment]
I was not too quick, you have to include `virtualgaragedooropener` device_type. This is not meant to be antagonistic, its supposed to be a community where people collaborate...

**Comment by TheEngineerGuy** [comment]
Yep we are all working together. All good.

**Comment by hjdhjd** [comment]
Likewise. Nobody's trying to be antagonistic...quite the contrary. It's good to have more eyes looking at this and collaborating. :smile:

**Comment by hjdhjd** [comment]
@TheEngineerGuy what are the physical devices in question that you have? @shamoon mentioned above about a particular device type, but I've never seen it anywhere, so I'm curious, before I add in support for it.

**Comment by TheEngineerGuy** [comment]
I just have a garage door opener, that's it.

So, it has a built in GW and Opener.

**Comment by hjdhjd** [comment]
Should be fixed in 2.0.7.

**Comment by jadtec87** [comment]
I see it now and it works! thanks!

**Comment by deanliou** [comment]
I just installed homebridge, homebridge config ui x, tplink, and this myq2 about an hour and a half ago.  I must have gotten 2.0.3 at the time installed. I was watching this issue and the other api 404 issue in real-time as you all were discussing. I did 2.0.5 and then this 2.0.7 just minutes ago. Pretty excited to have been able to watch this all come together. Many thanks to all of you!

**Comment by TheEngineerGuy** [comment]
Updated to 2.0.7 cleared accessories and persist cache, restarted HB. Still the same, no door in accessories list.

[7/4/2020, 12:46:44 AM] [myQ] Successfully connected to the myQ API.
[7/4/2020, 12:46:45 AM] [myQ] myQ garagedoor device discovered: Garage Door - CGxxxxx.
[7/4/2020, 12:46:45 AM] [myQ] myQ gateway device discovered: Garage Door - GWxxxxxx.

**Comment by hjdhjd** [comment]
@TheEngineerGuy I gotta believe the accessory is there somewhere. Check the default room, or the homebridge bridge in the Home app?

**Comment by hjdhjd** [comment]
@deanliou Thanks...that's the fun of being in a community like this, and meeting folks like @shamoon.

**Comment by TheEngineerGuy** [comment]
I am just not getting the third log entry that another person reported "Adding ......" I only get discovery, and that's it.

**Comment by cuellarfr** [comment]
Same here, accessory is still missing

**Comment by hjdhjd** [comment]
Fixed in 2.0.8.

**Comment by cuellarfr** [comment]
Working now. Thanks!
