### ISSUE TITLE
Closing and Opening States Aren't Updated Consistently.

### ISSUE THREAD

**Issue by andrewturko** [hjdhjd/homebridge-myq2#62]
Garage Door accessory state accuracy in home app is unreliable. Current state is:
- Toggle door closed: “Closing...”, stays hung up until force close. Sometimes, force close does not work, and a tap on accessory is only thing to clear it to correct state.
- Toggle door open: Immediately jumps to “Open”, with no “Opening...” state.

Config value overrides for OpenDuration and CloseDuration do not alter this behavior. 

This has an impact on automation functionality due to incorrect state being passed. This issue is similar but not entirely related to #53.

**Comment by TheEngineerGuy** [comment]
Hey @andrewturko This doesn't seem to be happening on my Home app. Is there a way to recreate this?

**Comment by TheEngineerGuy** [comment]
Yes, I can confirm this does happen. Which is quite weird.

**Comment by abhollan** [comment]
This is happening to me too. Relatedly, if I close the garage door using the Home app, it goes straight from ‘open’ to ‘close’ while the door is still closing, without ever actually saying ‘closing’ like it used to.

**Comment by jadtec87** [comment]
same here.  Though if i close the home app and open it again i see it say opening or closing.

**Comment by gizmotronic** [comment]
I'm seeing the problem as originally described. Worse, while I was able to control the door about 12 hours ago, nothing happens at all when I use either the Home or Eve apps.

**Comment by hjdhjd** [comment]
@abhollan That's known behavior...I'll be dealing with this separately at a later point, but it's a cosmetic not a functional issue and HomeKit is weird about closing and opening states at times.

**Comment by hjdhjd** [comment]
If someone has a reproducible, functionality issue, please do let me know. Otherwise if it's the cosmetics of saying opening and closing...yeah, I know. I'll deal with this in the coming updates at some point, but it's not high on my TODO list right now. I want to ensure functional blockers are dealt with, then finish restoring any missing functionality, and then look to add new things potentially. One step at a time.

I've tested this for a couple of weeks, I haven't been able to make it fail unless I'm doing very unnatural things to the plugin...so if you guys find a functional issue, please raise an issue.

**Comment by hjdhjd** [comment]
@andrewturko The config override values you speak of don't have as much to do with whether or not HomeKit shows closing or opening states. They are intended to provide additional resolution during key events to ensure we get timely updates back from myQ.

The plugin, quite intentionally at the moment, isn't trying to set closing and opening states right now.

**Comment by TheEngineerGuy** [comment]
Hi @hjdhjd , it is more than cosmetic my friend. When it gets stuck in a closing or opening state, notifications don't happen. So, definitely a functionality problem.

**Comment by hjdhjd** [comment]
Let me play with this. Stay tuned.

**Comment by TheEngineerGuy** [comment]
Thanks @hjdhjd

**Comment by andrewturko** [comment]
This issue has a potential affect on not only
visual accuracy, but the aforementioned notifications and automations too. I appreciate all the hard work you’ve put into this, thank you. @hjdhjd

**Comment by DMBlakeley** [comment]
Also observed the same behavior. Door is open or closed but HomeKit is reporting opening or closing. Touching the HomeKit icon reports the state as open or closed correctly.

@hjdhjd, would like to add my kudos to the excellent work you have done up upgrading this plugin to current programming standards!

**Comment by hjdhjd** [comment]
This is solved in 2.0.9...just off the presses.

**Comment by hjdhjd** [comment]
@DMBlakeley Thanks, much appreciated! Nice to hear positive feedback. :smile: Now let's hope I'm not getting too cocky that this is fixed in 2.0.9. :smile:

**Comment by hjdhjd** [comment]
There is still a known (to me) bug...if you start homebridge up and the door is currently open (instead of closed), the status will appear wrong in Home until you perform an action, and then it'll be fine. I need to spend some time tracking that down...but I view that truly as a minor annoyance for right now.

**Comment by DMBlakeley** [comment]
On a sample of 1 open/close cycle (don’t want the neighbors to think I am going crazy) the closed/opening/open/closing/closed logging was correct, HomeKit provided notifications, and the status was shown correctly on the HomeKit tile.

**Comment by hjdhjd** [comment]
@DMBlakeley How on earth do you think I've been debugging this thing all day? The neighbors definitely think I'm insane at this point, or that the poor guy next door doesn't realize he has gremlins in his garage! 😆

**Comment by DMBlakeley** [comment]
Glad to see that you still have a sense of humor given the probably 200+ comments/responses that you have been fielding in the last 24 hours!!!

**Comment by hjdhjd** [comment]
My best response here would probably be: no comment. 💯 

I think people may ultimately mean well, but often don't realize how difficult and entitled they may come across. This is a labor of love, as are my other projects...but I also have an actual life and surprisingly, it doesn't revolve around reverse engineering the myQ protocol or poking around in the bowels of HomeKit. It's all good though...just gotta remember that most people mean well most of the time...and the (sometimes vocal) minority that mean well, but don't realize how they come across...well...you gotta learn to live and work with everyone somehow.

Wow this is longer than I expected it to be. Seriously...it's all good. Happy to contribute to the community where I can.

**Comment by TheEngineerGuy** [comment]
Good stuff @hjdhjd . It is fixed, can confirm. Thank you again for your efforts my friend.

**Comment by hjdhjd** [comment]
Closing this issue out guys...feel free to open a new one if a problem reoccurs.

**Comment by andrewturko** [comment]
@hjdhjd Thank you for your prompt, continuous effort to keep this working fully. FWIW, I can also confirm I haven’t had an issue since update after using with several automations.

**Comment by hjdhjd** [comment]
@andrewturko Glad it hear it! Thanks for helping troubleshoot and track this down.
